{
  "exclude": {
    "files": "^.pre-commit-config.yaml$",
    "lines": null
  },
  "generated_at": "2023-06-13T18:09:10Z",
  "plugins_used": [
    {
      "name": "AWSKeyDetector"
    },
    {
      "name": "ArtifactoryDetector"
    },
    {
      "name": "AzureStorageKeyDetector"
    },
    {
      "base64_limit": 4.5,
      "name": "Base64HighEntropyString"
    },
    {
      "name": "BasicAuthDetector"
    },
    {
      "name": "BoxDetector"
    },
    {
      "name": "CloudantDetector"
    },
    {
      "ghe_instance": "github.ibm.com",
      "name": "GheDetector"
    },
    {
      "name": "GitHubTokenDetector"
    },
    {
      "hex_limit": 3,
      "name": "HexHighEntropyString"
    },
    {
      "name": "IbmCloudIamDetector"
    },
    {
      "name": "IbmCosHmacDetector"
    },
    {
      "name": "JwtTokenDetector"
    },
    {
      "keyword_exclude": null,
      "name": "KeywordDetector"
    },
    {
      "name": "MailchimpDetector"
    },
    {
      "name": "NpmDetector"
    },
    {
      "name": "PrivateKeyDetector"
    },
    {
      "name": "SlackDetector"
    },
    {
      "name": "SoftlayerDetector"
    },
    {
      "name": "SquareOAuthDetector"
    },
    {
      "name": "StripeDetector"
    },
    {
      "name": "TwilioKeyDetector"
    }
  ],
  "results": {
    "test/test-app-rest/src/main/webapp/index.html": [
      {
        "hashed_secret": "ad9328812a2bf947a81f8b3422047a194d152ecf",
        "is_verified": false,
        "line_number": 27,
        "type": "Base64 High Entropy String",
        "verified_result": null
      },
      {
        "hashed_secret": "f1c4dfa73a7a850bb18efdee6a07af0999235185",
        "is_verified": false,
        "line_number": 64,
        "type": "Base64 High Entropy String",
        "verified_result": null
      }
    ]
  },
  "version": "0.13.1+ibm.47.dss",
  "word_list": {
    "file": null,
    "hash": null
  }
}
