name: Open Liberty S2I Continuous Integration
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'docs/**'
env:
  LANG: en_US.UTF-8
  S2I_URI: https://api.github.com/repos/openshift/source-to-image/releases/tags/v1.3.8
  CEKIT_VERSION: 4.8.0
jobs:
  olci:
    name: Open Liberty S2I Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR ID
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{github.token}}
          script: |
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);
      - name: Verify latest centos image is present
        run: |
          docker image ls | grep centos || true
          docker pull centos:7
          docker pull centos/s2i-base-centos7
          docker image ls | grep centos
      - name: Setup required system packages
        run: |
          echo PULL NUMBER: ${PULL_NUMBER}
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update
          sudo apt-get install krb5-multidev libkrb5-dev
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.6'
      - name: Setup virtualenv and install cekit and required packages
        run: |
          python --version
          sudo pip install virtualenv
          mkdir ~/cekit${{ env.CEKIT_VERSION }}
          python3 -m venv ~/cekit${{ env.CEKIT_VERSION }}
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          pip install cekit==${{ env.CEKIT_VERSION }} docker==5.0.3 docker-squash odcs behave lxml urllib3==1.26.15 packaging==21.3 requests==2.31.0
      - name: install s2i binary
        run: |
          echo ===== Installing s2i from ${{ env.S2I_URL }} =====
          mkdir /tmp/s2i/ && cd /tmp/s2i/
          curl -s ${{ env.S2I_URI }} \
           | grep browser_download_url \
           | grep linux-amd64 \
           | cut -d '"' -f 4 \
           | wget -qi -
           tar xvf source-to-image*.gz
           sudo mv s2i /usr/bin
           which s2i
           s2i version
      - name: Build and Run Tests
        run: |
          . ~/cekit${{ env.CEKIT_VERSION }}/bin/activate
          make test
          docker image ls

  
